### ISSUE TITLE
complexity for `adjust` 

### ISSUE THREAD

**Issue by MangoIV** [phadej/skew-list#1]
Hi, I think this is exactly what I need as far as I can tell, perfect timing, thank you for this, however, one thing isn't clear to me; what is the complexity for `adjust`, can you please give a quick answer without me digging into the impl? 

Thanks in advance.

**Comment by phadej** [comment]
`adjust` needs O(log n) time to find a tree to change. Than it will change that tree and the initial part of list-of-trees up to that. It's all around O(log n); but I'm not sure.

**Comment by MangoIV** [comment]
That's good to know. Thank you for making this an also for your quick answer. 

Something completely offtopic, but do you perhaps know an implementation of dynamic arrays in Haskell?

Thanks in advance.

**Comment by phadej** [comment]
What you mean by *dynamic arrays*? dynamic size, dynamic element types?

**Comment by MangoIV** [comment]
Dynamic size and O(1) indexing and updating that’d be

**Comment by phadej** [comment]
There are mutable vectors and arrays which support resizing. I'm not aware anyone have build anything on top of that to make using them more convenient.

**Comment by MangoIV** [comment]
Right, thank you anyway!
